blog/urls.py
from django.urls import path

from blog.views import *

app_name = "blog"

urlpatterns = (
    [
        path("", index, name="index"),
        path("authors/", AuthorListView.as_view(), name="author-list"),
        path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
        path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
        path("authors/<int:pk>/update/", AuthorUpdateView.as_view(), name="author-update"),
        path("authors/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
        path("themes/", ThemeListView.as_view(), name="theme-list"),
        path("themes/<int:pk>/", ThemeDetailView.as_view(), name="theme-detail"),
        path("themes/<int:pk>/edit/", ThemeEditView.as_view(), name="theme-edit"),
        path("themes/<int:pk>/delete/", ThemeDeleteView.as_view(), name="theme-delete"),
        path("themes/create/", ThemeCreateView.as_view(), name="theme-create"),
        path("articles/", ArticleListView.as_view(), name="article-list"),
        path("articles/<str:slug>/", ArticleDetailView.as_view(), name="article-detail"),
        path("articles/<str:slug>/edit/", ArticleEditView.as_view(), name="article-edit"),
        path("article-images/<int:pk>/delete/", ArticleImagesDeleteView.as_view(), name="article_image-delete"),
        path("article/create/", ArticleCreateView.as_view(), name="article-create"),
        path("article/<str:slug>/delete/", ArticleDeleteView.as_view(), name="article-delete"),
        path("comments/create/", CommentCreateView.as_view(), name="comment-create"),
    ]
)

core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("accounts/", include("django.contrib.auth.urls")),
        path("", include("blog.urls", namespace="blog")),
    ] + debug_toolbar_urls()
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

templates/includes/pagination.html
{% if  is_paginated %}
  <div class="pagination">
    <span class="page-links">
  {% if page_obj.has_previous %}
    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
      Prev
    </a>
  {% endif %}
      <span class="page-current">
        {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
  </span>
  </div>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.get_username }}</li>
    <li class="list-group-item">
      <form method="post" action="{% url "logout" %}" id="logout-form">
        {% csrf_token %}
        <button type="submit" class="btn btn-link">Logout</button>
      </form>
    </li>
  {% else %}
    <li class="list-group-item">
      <a href="{% url 'login' %}?next={{ request.path }}">
        Login
      </a>
    </li>
  {% endif %}
  <li class="list-group-item">
    <a href="{% url "blog:author-list" %}">Authors</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "blog:theme-list" %}">Themes</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "blog:article-list" %}">Articles</a>
  </li>
</ul>