blog/urls.py
from django.urls import path

from blog.views import *

app_name = "blog"

urlpatterns = (
    [
        path("", index, name="index"),
        path("authors/", AuthorListView.as_view(), name="author-list"),
        path("authors/create/", AuthorCreateView.as_view(), name="author-create"),
        path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author-detail"),
        path("authors/<int:pk>/update/", AuthorUpdateView.as_view(), name="author-update"),
        path("authors/<int:pk>/delete/", AuthorDeleteView.as_view(), name="author-delete"),
        path("themes/", ThemeListView.as_view(), name="theme-list"),
        path("themes/<int:pk>/", ThemeDetailView.as_view(), name="theme-detail"),
        path("themes/<int:pk>/edit/", ThemeEditView.as_view(), name="theme-edit"),
        path("themes/<int:pk>/delete/", ThemeDeleteView.as_view(), name="theme-delete"),
        path("themes/create/", ThemeCreateView.as_view(), name="theme-create"),
        path("articles/", ArticleListView.as_view(), name="article-list"),
        path("articles/<str:slug>/", ArticleDetailView.as_view(), name="article-detail"),
        path("articles/<str:slug>/edit/", ArticleEditView.as_view(), name="article-edit"),
        path("article-images/<int:pk>/delete/", ArticleImagesDeleteView.as_view(), name="article_image-delete"),
        path("article/create/", ArticleCreateView.as_view(), name="article-create"),
        path("article/<str:slug>/delete/", ArticleDeleteView.as_view(), name="article-delete"),
        path("comments/create/", CommentCreateView.as_view(), name="comment-create"),
    ]
)

core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("accounts/", include("django.contrib.auth.urls")),
        path("", include("blog.urls", namespace="blog")),
    ] + debug_toolbar_urls()
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

blog/models.py
from cloudinary.models import CloudinaryField
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Author(AbstractUser):
    avatar = CloudinaryField("avatar")

    class Meta:
        verbose_name = "author"
        verbose_name_plural = "authors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("blog:author-detail", kwargs={"pk": self.pk})


class Theme(models.Model):
    name = models.CharField(
        max_length=255, unique=True, blank=False, null=False
    )

    class Meta:
        ordering = ["name"]
        indexes = [
            models.Index(fields=['name', ])
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:theme-detail", kwargs={"pk": self.pk})


class Article(models.Model):
    title = models.CharField(
        max_length=255, unique=True, blank=False, null=False
    )
    description = models.TextField(
        max_length=500,
    )
    themes = models.ManyToManyField(
        Theme,
        related_name="articles"
    )
    content = models.TextField()
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.RESTRICT,
        related_name="articles"
    )

    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(default="", null=False)

    class Meta:
        ordering = ["title"]
        indexes = [
            models.Index(fields=['title', ])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:article-detail", kwargs={"slug": self.slug})


class Comments(models.Model):
    text = models.TextField()
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Comments"

    def __str__(self):
        return f"{self.text[:50]}..."


class ArticleImages(models.Model):
    picture = CloudinaryField("picture")
    article = models.ForeignKey(
        Article,
        on_delete=models.CASCADE,
        related_name="pictures"
    )

    class Meta:
        verbose_name_plural = "Article images"

    def __str__(self):
        return self.article.title

    def get_author(self):
        return self.article.author.username

    get_author.short_description = 'author'

blog/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from blog.models import Article


class ArticleEditForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "description", "themes", "content",)


class AuthorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "email", "avatar",
        )


class AuthorUpdateForm(UserChangeForm):
    avatar = CloudinaryFileField(required=False)

    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "last_name", "email", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if "password" in self.fields:
            del self.fields["password"]

blog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views import generic, View

from blog.forms import ArticleEditForm, AuthorCreationForm, AuthorUpdateForm
from blog.models import Theme, Article, ArticleImages, Comments


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_authors = get_user_model().objects.count()
    num_themes = Theme.objects.count()
    num_articles = Article.objects.count()

    num_visits = request.session.get("num_visits", 0)
    num_visits += 1
    request.session["num_visits"] = num_visits

    ctx = {
        "num_authors": num_authors,
        "num_themes": num_themes,
        "num_articles": num_articles,
        "num_visits": num_visits,
    }
    return render(request, "blog/index.html", ctx)


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = get_user_model()
    paginate_by = 10


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = get_user_model()


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = get_user_model()
    form_class = AuthorCreationForm


class AuthorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = get_user_model()
    form_class = AuthorUpdateForm


class AuthorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = get_user_model()
    success_url = reverse_lazy("blog:author-list")


class ThemeListView(LoginRequiredMixin, generic.ListView):
    model = Theme
    paginate_by = 10


class ThemeDetailView(LoginRequiredMixin, generic.DetailView):
    model = Theme


class ThemeCreateView(LoginRequiredMixin, generic.CreateView):
    model = Theme
    fields = "__all__"

    def get_success_url(self):
        return reverse_lazy("blog:theme-list")


class ThemeEditView(LoginRequiredMixin, generic.UpdateView):
    model = Theme
    fields = "__all__"


class ThemeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Theme
    success_url = reverse_lazy("blog:theme-list")


class ArticleListView(LoginRequiredMixin, generic.ListView):
    model = Article
    paginate_by = 10

    def get_queryset(self):
        return (
            Article.objects
            .select_related("author")
            .prefetch_related("themes")
        )


class ArticleDetailView(LoginRequiredMixin, generic.DetailView):
    model = Article

    def get_queryset(self):
        return (
            Article.objects
            .select_related("author")
        )


class ArticleEditView(LoginRequiredMixin, generic.UpdateView):
    model = Article
    form_class = ArticleEditForm

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data(**kwargs)
        pictures = self.object.pictures.all()
        ctx["picture_list"] = pictures
        return ctx

    def form_valid(self, form):
        try:
            with transaction.atomic():
                self.object = form.save()

                pictures = self.request.FILES.getlist('new_pictures')

                objs = (
                    ArticleImages(article=self.object, picture=picture)
                    for picture in pictures
                )
                ArticleImages.objects.bulk_create(objs)

                return super().form_valid(form)

        except Exception:
            return self.form_invalid(form)


class ArticleImagesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = ArticleImages
    template_name = "blog/articleimages_confirm_delete.html"

    def get_success_url(self):
        return reverse("blog:article-edit", kwargs={'slug': self.object.article.slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['slug'] = self.object.article.slug
        return context


class ArticleCreateView(LoginRequiredMixin, generic.CreateView):
    model = Article
    form_class = ArticleEditForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        try:
            with transaction.atomic():
                response = super().form_valid(form)

                pictures = self.request.FILES.getlist('new_pictures')

                objs = (
                    ArticleImages(article=self.object, picture=picture)
                    for picture in pictures
                )
                ArticleImages.objects.bulk_create(objs)
                return response

        except Exception:
            return self.form_invalid(form)


class ArticleDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Article

    def get_success_url(self):
        return reverse_lazy("blog:article-list")


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request):
        content = request.POST.get('comment-content')
        article_slug = request.POST.get('article_slug')

        article = get_object_or_404(Article, slug=article_slug)

        Comments.objects.create(
            text=content,
            article=article,
            author=request.user
        )

        return redirect('blog:article-detail', slug=article_slug)

templates/blog/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete article?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <a href="{% url "blog:article-detail" slug=article.slug %}">Cancel</a>
{% endblock %}

templates/blog/article_detail.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
  <h1>{{ article.title }}</h1>
  {% for img in article.pictures.all %}
    {% cloudinary img.picture quality="auto" width="200" height="100" crop="pad" background="gen_fill:ignore-foreground_true" %}
  {% endfor %}
  <p><strong>Short description: </strong> {{ article.description }}</p>
  <ul>
    <li>
      Written by:
      <a href="{{ article.author.get_absolute_url }}">
        {{ article.author.username }}
      </a>
    </li>
    <li> Created at: {{ article.created_at }}</li>
  </ul>
  <p>Themes: </p>
  <ul>
    {% for theme in  article.themes.all %}
      <li>
        <a href="{{ theme.get_absolute_url }}">{{ theme.name }}</a>
      </li>
    {% empty %}
      <p>No theme yet</p>
    {% endfor %}
  </ul>
  <br>
  <p>{{ article.content }}</p>
  <br>
  <a href="{% url "blog:article-edit" slug=article.slug %}" class="btn btn-warning">Edit</a>
  <a href="{% url "blog:article-delete" slug=article.slug %}" class="btn btn-danger">Delete</a>
  <br>
  <br>
  <p><strong><label for="area">Add new comment:</label></strong></p>
  <form action="{% url "blog:comment-create" %}" method="post">
    {% csrf_token %}
    <textarea id="area" name="comment-content">type here</textarea>
    <input type="submit" value="Add" class="btn btn-success">
    <input type="hidden" name="article_slug" value = "{{ article.slug }}">
  </form>
  <h4>Comments</h4>
  {% for comment in article.comments.all %}
    <ul>
      <li>
        {{ comment.author.username }}
        {% cloudinary comment.author.avatar quality="auto" width="50" height="50" crop="fill" gravity="face" %}
      </li>
      <li>
        {{ comment.text }}
      </li>
      <li>
        {{ comment.created_at }}
      </li>
    </ul>
  {% endfor %}
{% endblock %}

templates/blog/article_form.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Article </h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <br>
    <p><strong>Images:</strong></p>
    {% if picture_list %}
      <table>
        {% for img in picture_list %}
          <tr>
            <td>
              {% cloudinary img.picture quality="auto" width="200" height="100" crop="pad" background="gen_fill:ignore-foreground_true" %}
            </td>
            <td>
              <a href="{% url 'blog:article_image-delete' pk=img.pk %}"
                 class="btn btn-danger btn-sm">
                Delete
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p> no pictures </p>
    {% endif %}
    <h3>Add New Images</h3>
    <label for="new_pictures">Upload new pictures:</label>
    <input type="file"
           id="new_pictures"
           name="new_pictures"
           accept="image/*"
           multiple
           class="form-control">
    <small class="form-text text-muted">You can select multiple images at once</small>

    <input type="submit" value="Submit"/>
  </form>
  <a href="{% url "blog:article-list" %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/blog/article_list.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header">
    <h1>
      Articles
    </h1>
    <a href="{% url "blog:article-create" %}" class="btn btn-primary">&#43;</a>
  </div>
  {% if article_list %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">
          #
        </th>
        <th scope="col">
          Title
        </th>
        <th scope="col">
          Description
        </th>
        <th scope="col">
          Theme
        </th>
        <th scope="col">
          Author
        </th>
      </tr>
      </thead>
      <tbody>
      {% for article in article_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <a href="{{ article.get_absolute_url }}">
              {{ article.title }}
            </a>
          </td>
          <td>
            {{ article.description }}
          </td>
          <td>
            <ul class="list-unstyled list-inline">
              {% for theme in article.themes.all %}
                <li>
                  <a href="{{ theme.get_absolute_url }}">
                    {{ theme.name }}
                  </a>
                </li>
              {% endfor %}
            </ul>
          </td>
          <td>
            <a href="{{ article.author.get_absolute_url }}">
              {{ article.author.username }}
            </a>

          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no authors yet</p>
  {% endif %}
{% endblock %}

templates/blog/articleimages_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete image?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <a href="{% url "blog:article-edit" slug=slug %}">Cancel</a>
{% endblock %}

templates/blog/author_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Author?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <a href="{% url "blog:author-detail" pk=author.pk %}">Cancel</a>
{% endblock %}

templates/blog/author_detail.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
  <div class="page-header">
    <h1>
      Author: {{ author.username }}
    </h1>
    {% cloudinary author.avatar quality="auto" width="200" height="100" crop="pad" background="gen_fill:ignore-foreground_true" %}
    <div>
      <a href="{% url "blog:author-update" pk=author.pk %}" class="btn btn-success">Update</a>
      <a href="{% url "blog:author-delete" pk=author.pk %}" class="btn btn-danger">Delete</a>
    </div>
  </div>

  <h4> Articles </h4>
  {% for article in author.articles.all %}
    <ul>
      <li>
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
      </li>
    </ul>
  {% empty %}
    <p>No articles yes</p>
  {% endfor %}
  <h4>Comments</h4>
  {% if author.comments.all %}
    <table class="table table-striped">
      {% for comment in author.comments.all %}
        <thead>
        <tr>
          <th scope="col">
            #
          </th>
          <th scope="col">
            Article
          </th>
          <th scope="col">
            Created at
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <a href="{{ comment.article.get_absolute_url }}">
              {{ comment.article.title }}</a>
          </td>
          <td>
            {{ comment.created_at }}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>No comments yet</p>
  {% endif %}
{% endblock %}

templates/blog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Author </h1>
  <form action="" method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit"/>
  </form>
  <a href="{% url "blog:author-list" %}" class="btn btn-secondary">Cancel</a>
{% endblock %}

templates/blog/author_list.html
{% extends "base.html" %}
{% load cloudinary %}

{% block content %}
  <div class="page-header">
    <h1>Authors</h1>
    <a href="{% url "blog:author-create" %}" class="btn btn-primary">&#43;</a>
  </div>
  {% if author_list %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">
          #
        </th>
        <th scope="col">
          Author first and last name
        </th>
        <th scope="col">
          Author avatar
        </th>
      </tr>
      </thead>
      <tbody>
      {% for author in author_list %}
        <tr>
          <th scope="row">{{ author.id }}</th>
          <td>
            <a href="{{ author.get_absolute_url }}">
              {{ author.username }}
            </a>
          </td>
          <td>
            {% cloudinary author.avatar quality="auto" width="200" height="100" crop="pad" background="gen_fill:ignore-foreground_true" %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no authors yet</p>
  {% endif %}
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}

{% block content %}
  <h1>My Blog Home</h1>
  <p>Welcome to my Blog!</p>
  <h2>Nerd stats</h2>
  <p>My Blog service has the following record counts:</p>
  <ul>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
    <li><strong>Themes:</strong> {{ num_themes }}</li>
    <li><strong>Articles:</strong> {{ num_articles }}</li>
  </ul>
  <p>
    You visited my blog {{ num_visits }}
    time{{ num_visits|pluralize }}
  </p>
{% endblock %}

templates/blog/theme_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete theme?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
  <a href="{% url "blog:theme-list" %}">Cancel</a>
{% endblock %}

templates/blog/theme_detail.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header">
    <h1>
      Theme: {{ theme.name }}
    </h1>
    <div>
      <a href="{% url "blog:theme-edit" pk=theme.pk %}" class="btn btn-success">
        Edit
      </a>
      <a href="{% url "blog:theme-delete" pk=theme.pk %}" class="btn btn-danger">
        Delete
      </a>
    </div>
  </div>
  <h4> Articles </h4>
  {% for article in theme.articles.all %}
    <ul>
      <li>
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
      </li>
    </ul>
  {% empty %}
    <p>No articles yet</p>
  {% endfor %}
{% endblock %}

templates/blog/theme_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Theme </h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
  </form>
  <a href="{% url "blog:theme-list" %}" class=" btn btn-secondary">Cancel</a>
{% endblock %}

templates/blog/theme_list.html
{% extends "base.html" %}

{% block content %}
  <div class="page-header">
    <h1>Themes</h1>
    <a href="{% url "blog:theme-create" %}" class="btn btn-primary">&#43;</a>
  </div>
  {% if theme_list %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th scope="col">
          #
        </th>
        <th scope="col">
          Name
        </th>
      </tr>
      </thead>
      <tbody>
      {% for theme in theme_list %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>
            <a href="{{ theme.get_absolute_url }}">
              {{ theme.name }}
            </a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>There are no themes yet</p>
  {% endif %}
{% endblock %}